language: python
python: 2.7
os:
  - linux
env:
  - TOX_ENV=qunit

matrix:
  include:
    - env: TOX_ENV=qunit
      addons:
        chrome: stable

install:
  - set -e
  - pip install tox

script: tox -e $TOX_ENV

notifications:
  email: false
