# Directory to host galaxy galaxy code.
executor_directory: /srv/executor
galaxy_prefix: /
galaxy_admin: galaxy-admin@example.org

data_share: '{{executor_directory}}/database'
tools_share: '{{executor_directory}}/tools'

# Directory which holds object store data. This directory is mounted to an nfs
# server.
object_store_directory: "{{ executor_directory }}/database"

# Directory which holds datasets of workflows. It's parent is
# `object_store_directory`.
files_directory: files

# tmp directory of jobs. It's parent is `object_store_directory`.
tmp_directory: tmp

# Galaxy remote repo.
galaxy_repo: https://github.com/madgik/galaxy

# Version of the repository to check out. A branch, a tag or a commit hash.
executor_version: release_19.01

# job runner
local_workers: 4

# Postgres
executor_db_name: executor
executor_db_user: executor
executor_db_password: executor

# Packages
docker_pkg: docker.io
